### ISSUE TITLE
when i make cm13.0 for thea, i find this problem

### ISSUE THREAD

**Issue by fashioncj** [CyanogenMod/android_device_motorola_thea#4]
make: *** no rule to create “XXX/out/target/product/thea/system/bin/adsprpcd” need target “vendor/motorola/msm8226-common/proprietary/bin/adsprpcd”. stop.

what's the step i need to do ?

**Comment by luk1337** [comment]
Add TheMuppets/proprietary_vendor_motorola to your roomservice.

**Comment by fashioncj** [comment]
@luk1337 thanks for reply, how can i use it ? Just add the git response to manifest?

**Comment by luk1337** [comment]
Yup, just add it to .repo/local_manifests/roomservice.xml

**Comment by fashioncj** [comment]
@luk1337 
`<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="CyanogenMod/android_device_motorola_thea" path="device/motorola/thea" remote="github" />
  <project name="CyanogenMod/android_device_motorola_msm8226-common" path="device/motorola/msm8226-common" remote="github" />
  <project name="CyanogenMod/android_device_qcom_common" path="device/qcom/common" remote="github" />
  <project name="CyanogenMod/android_kernel_motorola_msm8226" path="kernel/motorola/msm8226" remote="github" />
  <project name="TheMuppets/proprietary_vendor_motorola" path="kernel/motorola/msm8226" remote="github" />

</manifest>
`

what's the correct path ?

**Comment by luk1337** [comment]
vendor/motorola

**Comment by fashioncj** [comment]
vim .repo/local_manifests/roomservice.xml

 <project name="TheMuppets/proprietary_vendor_motorola" path="vendor/motorola" remote="github" />
