### ISSUE TITLE
Cellular data cannot be turned on

### ISSUE THREAD

**Issue by zzhhbyt1** [CyanogenMod/android_device_motorola_thea#5]
Sorry to bother here...
I flashed cm-13.0-20160519-NIGHTLY-thea.zip on my XT1079, (clean flash) and after boot up I can't use cellular data.
The button can be triggered normally in settings, but without any effect, the data counting don't appear, too.
It seems that somebody have reported this problem but it still not get fix up? http://forum.xda-developers.com/moto-g-lte/orig-development/rom-cyanogenmod-13-0-t3245547/post63903460#post63903460

China Telecom.
I'm new to GitHub and android, not clear what additional info I should provide. So if you want to know, just tell me, I'll try my best~

**Comment by luk1337** [comment]
Wait for today's build.

**Comment by zzhhbyt1** [comment]
Thank you for your reply, I'll try 0520 soon.
By the way, that reply is really cool. XD

**Comment by zzhhbyt1** [comment]
Things go well in 0520, thanks!
