### ISSUE TITLE
Can't flash open_gapps-arm-6.0-nano

### ISSUE THREAD

**Issue by zzhhbyt1** [CyanogenMod/android_device_motorola_thea#6]
Error `#20 - Incorrect (incompatible) ROM Version: ROM is not compatible with the Open GApps package`
`open_gapps_log.txt` says:
```
# Begin Open GApps Install Log
-----------------------------------------------------------------------------
           ROM Android Version | 5.1.1
-----------------------------------------------------------------------------
# End Open GApps Install Log

INSTALLATION FAILURE: This GApps package can only be installed on a 6.0.x ROM.


# Begin User's gapps-config

# End User's gapps-config
```

I'm not clear how do they check the rom version... And this is a odd thing...
Some GApps package without version check can be flash and run normally. E.G.: `gapps-600-base-20151016-1-signed.zip`

**Comment by luk1337** [comment]
That looks like an old OpenGapps bug, when did you download that package?

**Comment by zzhhbyt1** [comment]
20160218, hum, maybe too old?

**Comment by zzhhbyt1** [comment]
Quite hard to download OpenGApps in China...
The connection is to slow...

**Comment by luk1337** [comment]
Yeah, download fresh gapps.

**Comment by zzhhbyt1** [comment]
Sorry to bother, but recently I have no time to refresh CM and test new gapps and have to prepare for the final exam... I'm currently using another Gapps package which don't have a ROM version testing function. And everything go on well now.
Thank you for your effort!
And let me just close this issue as you have already known this is a problem due to older version.

**Comment by zzhhbyt1** [comment]
Tested using CM 0524 with OpenGApps 0524, the problem does not appear anymore! Thanks!
